### ISSUE TITLE
Improve the PR build to only verify the right code

### ISSUE THREAD

**Issue by qcastel** [OpenBankingToolkit/openbanking-aspsp#43]
When modifying the UI code, the PR pipeline is also checking the java code, which is quite slow.

An improvement could be to only do some java code check if the java code has been updated.

**Comment by shprink** [comment]
example:

```
on:
  push:
    paths:
      - ".github/workflows/ui.yml"
      - "forgerock-openbanking-ui/**"
```
